"""empty message

Revision ID: 6e1d6d5f903f
Revises: ab8a6281581f
Create Date: 2017-09-23 19:46:45.969295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e1d6d5f903f'
down_revision = 'ab8a6281581f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_red_packet_creator_id'), 'red_packet', ['creator_id'], unique=False)
    op.create_index(op.f('ix_red_packet_token'), 'red_packet', ['token'], unique=False)
    op.create_index('ix_token_and_owner_id', 'share', ['red_packet_token', 'owner_id'], unique=False)
    op.create_index(op.f('ix_user_api_key'), 'user', ['api_key'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_api_key'), table_name='user')
    op.drop_index('ix_token_and_owner_id', table_name='share')
    op.drop_index(op.f('ix_red_packet_token'), table_name='red_packet')
    op.drop_index(op.f('ix_red_packet_creator_id'), table_name='red_packet')
    # ### end Alembic commands ###
