"""empty message

Revision ID: ab8a6281581f
Revises: f7008f92ddb0
Create Date: 2017-09-23 17:49:11.580945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab8a6281581f'
down_revision = 'f7008f92ddb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('returned_credits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'returned_credits')
    # ### end Alembic commands ###
