"""empty message

Revision ID: f2e0340af133
Revises: 6e1d6d5f903f
Create Date: 2017-09-25 11:57:08.515000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e0340af133'
down_revision = '6e1d6d5f903f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_share_owner_id'), 'share', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_share_owner_id'), table_name='share')
    # ### end Alembic commands ###
